hydra:
  job:
    name: eval_novel
    chdir: false
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M}
  
output_dir: ${hydra:run.dir}
# ---------------------------------------------------------#
  
clear_output: True

eval:
  episode_num: 25
  episode_length: 50
  start_episode: 0
  headless: true
  device: 0

  model_paths: 
    region_match:  "./weights/region_match_44999.pth"
    invariant_region:  "./weights/invariant_region_44999.pth"
    region_match_fine:  "./weights/region_match_fine_40000.pth"

  agent:
    min_episodes_per_desc: -1
    support_episode: -1 # debug
    debug: False
    cache_to: "./datasets/episodes.pkl.novel"


testset_path: ./datasets/novel_tests
demoset_path: ./datasets/novel_demonstrations